//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flexstudio_for_OBS.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flexstudio_for_OBS.Languages.Lang_de", typeof(Lang_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue OBS Version herunterladen.
        /// </summary>
        internal static string addNewOBSbtn {
            get {
                return ResourceManager.GetString("addNewOBSbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichere.
        /// </summary>
        internal static string Backing_up {
            get {
                return ResourceManager.GetString("Backing up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichern.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherung konnte nicht erstellt werden. Fehler::.
        /// </summary>
        internal static string backupErrorHint {
            get {
                return ResourceManager.GetString("backupErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es muss mindestens eine Option für die Sicherung ausgewählt werden!.
        /// </summary>
        internal static string backupNeedsOneItemHint {
            get {
                return ResourceManager.GetString("backupNeedsOneItemHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügt die restlichen Daten (Programmdaten, Plugins, etc.) zur Datensicherung hinzu.
        /// </summary>
        internal static string backupOBSbinariesHint {
            get {
                return ResourceManager.GetString("backupOBSbinariesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügt das OBS Profil zur Datensicherung hinzu.
        /// </summary>
        internal static string backupOBSprofileHint {
            get {
                return ResourceManager.GetString("backupOBSprofileHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese OBS Version läuft noch..
        /// </summary>
        internal static string backupOBSstillRunning {
            get {
                return ResourceManager.GetString("backupOBSstillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherungen.
        /// </summary>
        internal static string Backups {
            get {
                return ResourceManager.GetString("Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherung {0} erfolgreich erstellt.
        /// </summary>
        internal static string backupSuccessHint {
            get {
                return ResourceManager.GetString("backupSuccessHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensicherung.
        /// </summary>
        internal static string btnBackup {
            get {
                return ResourceManager.GetString("btnBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string btnDashboard {
            get {
                return ResourceManager.GetString("btnDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade ausgewählte Version herunter.
        /// </summary>
        internal static string btnDownloadSelected {
            get {
                return ResourceManager.GetString("btnDownloadSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinde Standardlaufwerk.
        /// </summary>
        internal static string btnMapDrive {
            get {
                return ResourceManager.GetString("btnMapDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Versionen.
        /// </summary>
        internal static string btnOBSversions {
            get {
                return ResourceManager.GetString("btnOBSversions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte OBS.
        /// </summary>
        internal static string btnStartOBS {
            get {
                return ResourceManager.GetString("btnStartOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinde Standardlaufwerk beim Start der App.
        /// </summary>
        internal static string cbAutoMapDefaultDrive {
            get {
                return ResourceManager.GetString("cbAutoMapDefaultDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entferne Standardlaufwerk beim Schliessen der App.
        /// </summary>
        internal static string cbAutoRemoveDefaultDrive {
            get {
                return ResourceManager.GetString("cbAutoRemoveDefaultDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Standard OBS-Version beim Start der App.
        /// </summary>
        internal static string cbAutoStartOBS {
            get {
                return ResourceManager.GetString("cbAutoStartOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe einmal täglich auf Updates.
        /// </summary>
        internal static string cbCheckUpdatesDaily {
            get {
                return ResourceManager.GetString("cbCheckUpdatesDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiger Wert für die Einstellung &apos;autoMapDefaultDrive&apos; oder &apos;autoStartDefaultOBS&apos; erkannt. Fehler:.
        /// </summary>
        internal static string dashboardInvalidSettingHint {
            get {
                return ResourceManager.GetString("dashboardInvalidSettingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine Standard OBS Version eingestellt. Bitte mache dies im Menüpunkt OBS Versionen..
        /// </summary>
        internal static string dashboardNoDefaultOBSerror {
            get {
                return ResourceManager.GetString("dashboardNoDefaultOBSerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht eingestellt.
        /// </summary>
        internal static string dashboardOBSdefaultVersionNotSetHint {
            get {
                return ResourceManager.GetString("dashboardOBSdefaultVersionNotSetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laufwerk {0}: erfolgreich entfernt..
        /// </summary>
        internal static string dashboardRemovedMappedDriveSuccess {
            get {
                return ResourceManager.GetString("dashboardRemovedMappedDriveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This OBS version is already running but cannot be brought to the foreground. Do you want to terminate it and start a new instance?.
        /// </summary>
        internal static string dashboardUnresponsiveOBSinstanceWarning {
            get {
                return ResourceManager.GetString("dashboardUnresponsiveOBSinstanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche.
        /// </summary>
        internal static string deleteToolStripMenuItem {
            get {
                return ResourceManager.GetString("deleteToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen und Entpacken abgebrochen..
        /// </summary>
        internal static string Download_and_extraction_cancelled_ {
            get {
                return ResourceManager.GetString("Download and extraction cancelled.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen und entpacken erfolgreich abgeschlossen..
        /// </summary>
        internal static string Download_and_extraction_completed_successfully_ {
            get {
                return ResourceManager.GetString("Download and extraction completed successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade ausgewählte Version herunter.
        /// </summary>
        internal static string Download_selected_version {
            get {
                return ResourceManager.GetString("Download selected version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herunterladen oder Entpacken läuft noch. Dies wird abgebrochen, wenn das Fenster geschlossen wird. Fortfahren?.
        /// </summary>
        internal static string downloadOBScancelWarning {
            get {
                return ResourceManager.GetString("downloadOBScancelWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entpacken.
        /// </summary>
        internal static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis existiert bereits.
        /// </summary>
        internal static string Folder_exists {
            get {
                return ResourceManager.GetString("Folder exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Zielverzeichnis existiert bereits. Soll es überschrieben werden oder die Aktion abgebrochen werden?{newline}{newline}Ja - Überschreiben{newline}Nein - Umbenennen{newline}Abbrechen - Aktion abbrechen.
        /// </summary>
        internal static string formClosingWarningDownload {
            get {
                return ResourceManager.GetString("formClosingWarningDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das GitHub API Limit wurde erreicht. Bitte später nochmal versuchen..
        /// </summary>
        internal static string githubApiLimitReached {
            get {
                return ResourceManager.GetString("githubApiLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktionswünsche, Bug gefunden oder du möchtest bei der Übersetzung des Projekts helfen? Besuche die GitHub Projektseite..
        /// </summary>
        internal static string lblAppHint {
            get {
                return ResourceManager.GetString("lblAppHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wähle Standard Laufwerksbuchstabe:.
        /// </summary>
        internal static string lblDefaultDrive {
            get {
                return ResourceManager.GetString("lblDefaultDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Installation auf diesem PC.
        /// </summary>
        internal static string localOBSinstall {
            get {
                return ResourceManager.GetString("localOBSinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbinde Standardlaufwerk.
        /// </summary>
        internal static string Map_default_drive {
            get {
                return ResourceManager.GetString("Map default drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Standard Laufwerksbuchstabe ausgewählt. Einstellungen überprüfen.
        /// </summary>
        internal static string NoDefaultDriveSet {
            get {
                return ResourceManager.GetString("NoDefaultDriveSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noch nicht implementiert, sorry!.
        /// </summary>
        internal static string notImplementedYet {
            get {
                return ResourceManager.GetString("notImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS sichern.
        /// </summary>
        internal static string OBS {
            get {
                return ResourceManager.GetString("OBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Versionen.
        /// </summary>
        internal static string OBS_versions {
            get {
                return ResourceManager.GetString("OBS versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler aufgetreten. Fehler:.
        /// </summary>
        internal static string obsDownloadErrorHint {
            get {
                return ResourceManager.GetString("obsDownloadErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindestens eine OBS Version ist noch aktiv. Bitte beende diese vorm Entfernen des Laufwerks..
        /// </summary>
        internal static string obsStillRunning {
            get {
                return ResourceManager.GetString("obsStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Version.
        /// </summary>
        internal static string OBSversion {
            get {
                return ResourceManager.GetString("OBSversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese OBS Version läuft bereits..
        /// </summary>
        internal static string OBSversionAlreadyRunning {
            get {
                return ResourceManager.GetString("OBSversionAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicher, dass die ausgewählte Version gelöscht werden soll?.
        /// </summary>
        internal static string obsVersionConfirmDelete {
            get {
                return ResourceManager.GetString("obsVersionConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die OBS Version konnte nicht gelöscht werden. Fehler::.
        /// </summary>
        internal static string obsVersionErrorDeleteHint {
            get {
                return ResourceManager.GetString("obsVersionErrorDeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte entferne die lokale OBS Installation über die Systemsteuerung..
        /// </summary>
        internal static string obsVersionLocalDeleteHint {
            get {
                return ResourceManager.GetString("obsVersionLocalDeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Abrufen der OBS Versionen von GitHub. Prüfe Internetverbindung..
        /// </summary>
        internal static string obsVersionNoConnectionError {
            get {
                return ResourceManager.GetString("obsVersionNoConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die ausgewählte OBS Version ist noch aktiv. Bitte schliesse diese bevor du versuchst sie zu löschen..
        /// </summary>
        internal static string obsVersionRunningDeleteHint {
            get {
                return ResourceManager.GetString("obsVersionRunningDeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese OBS Version läuft bereits aber reagiert nicht. Soll sie beendet werden und erneut gestarten werden?.
        /// </summary>
        internal static string obsVersionRunningForegroundErrorHint {
            get {
                return ResourceManager.GetString("obsVersionRunningForegroundErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Version erfolgreich entfernt.
        /// </summary>
        internal static string obsVersionSuccessDeleteHint {
            get {
                return ResourceManager.GetString("obsVersionSuccessDeleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne Verzeichnis.
        /// </summary>
        internal static string openFolderToolStripMenuItem {
            get {
                return ResourceManager.GetString("openFolderToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfad zur OBS-Version.
        /// </summary>
        internal static string Path_to_OBS_version {
            get {
                return ResourceManager.GetString("Path to OBS version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wähle eine Version aus..
        /// </summary>
        internal static string Please_select_a_release_to_download_ {
            get {
                return ResourceManager.GetString("Please select a release to download.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil sichern.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        internal static string refreshBtn {
            get {
                return ResourceManager.GetString("refreshBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versionshinweise für.
        /// </summary>
        internal static string Release_notes_for {
            get {
                return ResourceManager.GetString("Release notes for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbleibend.
        /// </summary>
        internal static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entferne Laufwerk.
        /// </summary>
        internal static string Remove_drive {
            get {
                return ResourceManager.GetString("Remove drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiederherstellen.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Standard setzen.
        /// </summary>
        internal static string setAsDefaultToolStripMenuItem {
            get {
                return ResourceManager.GetString("setAsDefaultToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten.
        /// </summary>
        internal static string StartOBS {
            get {
                return ResourceManager.GetString("StartOBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string updateToolStripMenuItem {
            get {
                return ResourceManager.GetString("updateToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur OBS Versionen mit .ZIP-Datei werden hier angezeigt.
        /// </summary>
        internal static string versionHint {
            get {
                return ResourceManager.GetString("versionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Versionshinweise auf GitHub.
        /// </summary>
        internal static string View_release_notes_on_GitHub {
            get {
                return ResourceManager.GetString("View release notes on GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem beim Erstellen des virtuellen Laufwerks.
        /// </summary>
        internal static string virtualDriveCreationError {
            get {
                return ResourceManager.GetString("virtualDriveCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtuelles Laufwerk erfolgreich erstellt.
        /// </summary>
        internal static string virtualDriveCreationSuccess {
            get {
                return ResourceManager.GetString("virtualDriveCreationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem beim Entfernen des virtuellen Laufwerks.
        /// </summary>
        internal static string virtualDriveRemoveError {
            get {
                return ResourceManager.GetString("virtualDriveRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtuelles Laufwerk erfolgreich entfernt.
        /// </summary>
        internal static string virtualDriveRemoveSuccess {
            get {
                return ResourceManager.GetString("virtualDriveRemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine ZIP-Datei für diese Version gefunden..
        /// </summary>
        internal static string Zip_file_not_found_for_this_release_ {
            get {
                return ResourceManager.GetString("Zip file not found for this release.", resourceCulture);
            }
        }
    }
}
